(N) 2020-03-17T08:23:03 - qBittorrent v4.2.1 started
(N) 2020-03-17T08:23:03 - Using config directory: /home/abhisek/.config/qBittorrent/
(I) 2020-03-17T08:23:03 - Trying to listen on: 0.0.0.0:0,[::]:0
(N) 2020-03-17T08:23:03 - Peer ID: -qB4210-
(N) 2020-03-17T08:23:03 - HTTP User-Agent is 'qBittorrent/4.2.1'
(I) 2020-03-17T08:23:03 - DHT support [ON]
(I) 2020-03-17T08:23:03 - Local Peer Discovery support [ON]
(I) 2020-03-17T08:23:03 - PeX support [ON]
(I) 2020-03-17T08:23:03 - Anonymous mode [ON]
(I) 2020-03-17T08:23:03 - Encryption support [FORCED]
(I) 2020-03-17T08:23:03 - UPnP / NAT-PMP support [ON]
(W) 2020-03-17T08:23:03 - Couldn't load GeoIP database. Reason: No such file or directory
(N) 2020-03-17T08:23:03 - Options were saved successfully.
(I) 2020-03-17T08:23:03 - Successfully listening on IP: 127.0.0.1, port: TCP/40925
(I) 2020-03-17T08:23:03 - Successfully listening on IP: 127.0.0.1, port: UDP/40925
(I) 2020-03-17T08:23:03 - Successfully listening on IP: 130.89.132.41, port: TCP/41979
(I) 2020-03-17T08:23:03 - Successfully listening on IP: 130.89.132.41, port: UDP/41979
(I) 2020-03-17T08:23:03 - Successfully listening on IP: 192.168.122.1, port: TCP/43219
(I) 2020-03-17T08:23:03 - Successfully listening on IP: 192.168.122.1, port: UDP/43219
(I) 2020-03-17T08:23:03 - Successfully listening on IP: 10.64.97.67, port: TCP/45003
(I) 2020-03-17T08:23:03 - Successfully listening on IP: 10.64.97.67, port: UDP/45003
(I) 2020-03-17T08:23:03 - Successfully listening on IP: ::1, port: TCP/35881
(I) 2020-03-17T08:23:03 - Successfully listening on IP: ::1, port: UDP/35881
(I) 2020-03-17T08:23:03 - Successfully listening on IP: 2001:67c:2564:a305:686b:3d64:1d28:c3a4, port: TCP/38857
(I) 2020-03-17T08:23:03 - Successfully listening on IP: 2001:67c:2564:a305:686b:3d64:1d28:c3a4, port: UDP/38857
(I) 2020-03-17T08:23:03 - Successfully listening on IP: fe80::4004:78d5:1a4f:8fe0%wlan0, port: TCP/33921
(I) 2020-03-17T08:23:03 - Successfully listening on IP: fe80::4004:78d5:1a4f:8fe0%wlan0, port: UDP/33921
(I) 2020-03-17T08:23:03 - Successfully listening on IP: fc00:bbbb:bbbb:bb01::1:6142, port: TCP/34193
(I) 2020-03-17T08:23:03 - Successfully listening on IP: fc00:bbbb:bbbb:bb01::1:6142, port: UDP/34193
(I) 2020-03-17T08:23:03 - Successfully listening on IP: fe80::5dbc:ebd1:c6c0:e216%Mullvad-CH8, port: TCP/46411
(I) 2020-03-17T08:23:03 - Successfully listening on IP: fe80::5dbc:ebd1:c6c0:e216%Mullvad-CH8, port: UDP/46411
(N) 2020-03-17T08:23:03 - 'archlinux-2020.03.01-x86_64.iso' restored.
(W) 2020-03-17T08:23:03 - Couldn't download GeoIP database file. Reason: The remote host name was not found (invalid hostname)
(C) 2020-03-17T08:25:39 - UPnP/NAT-PMP: Port mapping failure, message: could not map port using UPnP: no router found
(C) 2020-03-17T08:25:39 - UPnP/NAT-PMP: Port mapping failure, message: could not map port using UPnP: no router found